name: xiebao19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '19 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiebao19871010
        env:
          tpcu17812: ${{ secrets.tpcu17812 }}
        run: |
          echo $tpcu17812 | jq -r .hsnfy530 | /bin/bash
          echo $lynel871 | jq -r .pw97178 | /bin/bash

